In [1]:
from pycoingecko import CoinGeckoAPI
from datetime import datetime, timezone, timedelta
import numpy as np
import pandas as pd

cg = CoinGeckoAPI()

Timestamp returned by this API are in UTC Timezone.

In [351]:
I = int((datetime(2021,2,16)-datetime(2018, 5, 25)).days/90)

In [353]:
# dt = datetime(2021, 2, 10)
# from_timestamp = dt.replace(tzinfo=timezone.utc).timestamp()

prices_pd_arr = []
dt = datetime(2018, 5, 25)
for i in range(I):
    from_timestamp = dt.replace(tzinfo=timezone.utc).timestamp()

    dt = dt+timedelta(days=+90)
    to_timestamp = dt.replace(tzinfo=timezone.utc).timestamp()

    prices = cg.get_coin_market_chart_range_by_id(id='bitcoin',
                                         vs_currency='USD',
                                         from_timestamp = from_timestamp,
                                         to_timestamp= to_timestamp)
    prices_pd = pd.DataFrame(prices['prices'])
    prices_pd_arr.append(prices_pd)

In [362]:
last_timestamp = datetime(2021,2,17)
last_timestamp = last_timestamp.replace(tzinfo=timezone.utc).timestamp()
prices = cg.get_coin_market_chart_range_by_id(id='bitcoin',
                                     vs_currency='USD',
                                     from_timestamp = to_timestamp,
                                     to_timestamp= last_timestamp)
prices_pd = pd.DataFrame(prices['prices'])
prices_pd_arr.append(prices_pd)

In [454]:
results = pd.concat(prices_pd_arr)
results = results.drop_duplicates()
results.columns = ['UTC_time', 'bitcoin price']

In [455]:
results.loc[:,'UTC_time'] = pd.to_datetime(results.loc[:,'UTC_time']*1000000)
results.loc[:,'berlin_time'] = results.loc[:,'UTC_time'].apply(lambda x: x+timedelta(hours=1))
results.loc[:,'berlin_time_date'] = results.loc[:,'UTC_time'].apply(lambda x: x.date())
results.loc[:,'berlin_time_hour'] = results.berlin_time.apply(lambda x:x.hour)
results.loc[:,'berlin_time_min'] = results.berlin_time.apply(lambda x:x.minute)
results.reset_index(drop=True, inplace=True)

In [468]:
results.to_csv('bitcoin_hourly_price_coingecko_raw.csv')

In [2]:
def time_diff(x, target_hour):
    y = x.year
    m = x.month
    d = x.day 
    return np.abs((x - datetime(y,m,d,target_hour)).total_seconds())

In [457]:
results.loc[:,'D'] = results.berlin_time.apply(lambda x: time_diff(x, 23))

In [4]:
results = pd.read_csv('../data/btc future and reference rate/bitcoin_hourly_price_coingecko_raw.csv')

In [5]:
date_arr = results.berlin_time_date.unique()

closest_to_23 = []

for date in date_arr:
    _id = results.berlin_time_date==date
    closest_to_23.append(np.argmin(results.loc[_id,'D']))

/Users/francis/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:56: FutureWarning:
The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
instead.
The behavior of 'argmin' will be corrected to return the positional
minimum in the future. For now, use 'series.values.argmin' or
'np.argmin(np.array(values))' to get the position of the minimum
row.
  return getattr(obj, method)(*args, **kwds)

In [9]:
bitcoin_price = results.iloc[closest_to_23,:].loc[:,['berlin_time_date', 'bitcoin price']]

In [10]:
bitcoin_price.reset_index(drop=True, inplace=True)

In [11]:
bitcoin_price

    berlin_time_date  bitcoin price
0         2018-05-25    7430.898613
1         2018-05-26    7426.048188
2         2018-05-27    7313.491701
3         2018-05-28    7170.130876
4         2018-05-29    7493.233637
5         2018-05-30    7342.441335
6         2018-05-31    7521.292835
7         2018-06-01    7422.044831
8         2018-06-02    7571.430080
9         2018-06-03    7638.067584
10        2018-06-04    7484.771980
11        2018-06-05    7564.335670
12        2018-06-06    7605.087170
13        2018-06-07    7604.170950
14        2018-06-08    7592.924282
15        2018-06-09    7522.996133
16        2018-06-10    6757.890083
17        2018-06-11    6786.297588
18        2018-06-12    6563.154775
19        2018-06-13    6295.864254
20        2018-06-14    6666.668431
21        2018-06-15    6478.536986
22        2018-06-16    6505.248392
23        2018-06-17    6456.269200
24        2018-06-18    6686.965985
25        2018-06-19    6681.538641
26        2018-06-20    6692.976817
27        2018-06-21    6678.695021
28        2018-06-22    6030.022932
29        2018-06-23    6215.402939
..               ...            ...
969       2021-01-18   36303.704379
970       2021-01-19   36419.483281
971       2021-01-20   34927.060093
972       2021-01-21   31284.024401
973       2021-01-22   33495.880668
974       2021-01-23   32359.011508
975       2021-01-24   31991.122791
976       2021-01-25   32429.912048
977       2021-01-26   32016.318284
978       2021-01-27   31038.167807
979       2021-01-28   33194.978393
980       2021-01-29   34975.625836
981       2021-01-30   34547.369013
982       2021-01-31   32623.901956
983       2021-02-01   33553.086495
984       2021-02-02   35615.923864
985       2021-02-03   37266.377988
986       2021-02-04   37574.981203
987       2021-02-05   37830.026647
988       2021-02-06   40385.350500
989       2021-02-07   38385.240892
990       2021-02-08   44500.739477
991       2021-02-09   47055.868087
992       2021-02-10   44864.924285
993       2021-02-11   46786.501690
994       2021-02-12   47695.120935
995       2021-02-13   47063.258882
996       2021-02-14   48742.100682
997       2021-02-15   48259.049758
998       2021-02-16   48605.801318

[999 rows x 2 columns]

https://www.coingecko.com/en/methodology

1. Price (Cryptoasset)
The price of a cryptoasset is calculated based on the pairings available and collected by CoinGecko from the various exchanges for a particular cryptoasset. The price shown on CoinGecko for a particular cryptoasset is calculated using a global volume-weighted average price formula.
Example 1 (Different fiat pairings)

Using Bitcoin (BTC) as an example, and assuming we only track two exchanges, A and B which trades in USD and JPY:

Exchange A: BTC/USD = USD 1,000 / BTC @ 15,000 BTC Trading Volume (rolling 24 hours)
Exchange B: BTC/JPY = JPY 109,000 / BTC @ 10,000 BTC Trading Volume (rolling 24 hours)
CoinGecko will first convert JPY to USD using FX rates provided by OpenExchangeRates. Assuming USD 1 = JPY 110, this will mean:

Exchange B: BTC/JPY = JPY 109,000 / BTC ≈ USD 990 / BTC

CoinGecko will then calculate the global volume-weighted average price. In this case, it will be:

CoinGecko BTC Price (USD)
= [Volume % * USD Price] + [Volume % * Converted USD Price]
= [ 15,000 / (15,000 + 10,000) ] * USD 1,000 + [ 10,000 / (15,000 + 10,000) ] * USD 990
= 0.6 * USD 1,000 + 0.4 * USD 990
= USD 996
Example 2 (Fiat & other crypto pairings)

Using Ethereum (ETH) as an example, and assuming we only track two exchanges, A and B which trades in USD and BTC:
Exchange A: ETH/USD = USD 200 / ETH @ 30,000 ETH Trading Volume (rolling 24 hours)
Exchange B: ETH/BTC = ₿ 0.20000000 / ETH @ 20,000 ETH Trading Volume (rolling 24 hours)
CoinGecko will first convert the ETH/BTC price to a USD price using the CoinGecko BTC Price derived above. Assuming 1 BTC = USD 996, this will mean:
Exchange B: ETH/BTC = ₿ 0.20000000 / ETH ≈ USD 199.2 / ETH

CoinGecko will then calculate the global volume-weighted average price. In this case, it will be:

CoinGecko ETH Price (USD)
= [ 30,000 / (30,000 + 20,000) ] * USD 200 + [ 20,000 / (30,000 + 20,000) ] * USD 199.2
= 0.6 * USD 200 + 0.4 * USD 199.2
= USD 199.68

From Example 1 and 2, the prices obtained in USD are then converted into other local currencies such as GBP, CNY, JPY, EUR and so on using OpenExchangeRates and then displayed on CoinGecko.

Note: CoinGecko’s global volume-weighted average price calculation excludes data points that are detected as outliers as explained in Part 3 below.